#!/bin/sh

#NOTE: this is just an internal helper script we call manually. It will never be called automaticly.

set -e

echo "ALPINEBOX: Adding DatuX ssh-keys"

wget -q -O - https://boot.datux.nl/keys >> ~/.ssh/authorized_keys

echo "ALPINEBOX: Done"
