#!/bin/sh
set -e

DISK=$1
if ! [ "$DISK" ]; then
    echo "Usage: $0 <disk>"
    echo "Will prepare disk and add it to your existing zpool mirror."

    echo "Will WIPE existing DATA on specified disk!"
    exit 1
fi

#sometimes the whole disk has an old label that confuses zfs after growing:
zpool labelclear -f $DISK &>/dev/null || true

export INSTALL_DISK=$DISK
export INSTALL_EFI_DEV=$DISK""2
export INSTALL_SWAP_DEV=$DISK""3
export INSTALL_ZPOOL_DEV=$DISK""4
export INSTALL_ZPOOL=${INSTALL_ZPOOL:-rpool}

cd install
./2-partition-disk.sh
./3-install-bootloader.sh

#add to pool
ZPOOL_DEV=`zpool list -P -L -H -v $INSTALL_ZPOOL|grep -v $INSTALL_ZPOOL|grep ONLINE|cut -f2|grep /|tail -1`
zpool attach -f $INSTALL_ZPOOL $ZPOOL_DEV $INSTALL_ZPOOL_DEV

zpool status

echo "ALPINEBOX: Done, check rebuild status with zpool status"
