#!/bin/sh

set -e 

echo "ALPINEBOX: Growing disks to use all available space"
ZPOOL_DEVS=`zpool list -P -L -H -v rpool|grep -v rpool|cut -f2|grep /`

#needs to be on, even tough its not going to be automatic.
zpool set autoexpand=on rpool

#important to prevent clashes with old labels in the unused space
zpool reguid rpool

for ZPOOL_DEV in $ZPOOL_DEVS; do
    DISK=`echo $ZPOOL_DEV | sed 's/p*[0-9]$//'`
    echo "ALPINEBOX: Repartitioning disk $DISK"

    #repartition
    sgdisk -d4 $DISK  || true
    sgdisk -n4:0:0 -t4:BF00 $DISK
    
    #reload
    partx -u $DISK 

    #grow
    zpool online rpool -e $ZPOOL_DEV || true

done

echo "ALPINEBOX: Result:"
zfs list rpool

echo "ALPINEBOX: Done"
