#!/bin/sh

set -e 

echo "ALPINEBOX: Growing disks to use all available space"
ZPOOL_DEVS=`zpool list -P -L -H -v rpool|grep -v rpool|cut -f2`

for ZPOOL_DEV in $ZPOOL_DEVS; do
    DISK=`echo $ZPOOL_DEV | sed 's/p*[0-9]$//'`
    echo "Repartitioning disk $DISK"
    sgdisk -d4 -n4:0:0 -t4:BF00 $DISK

done