#!/bin/sh

set -e

# dependencies
./install-docker

echo "ALPINEBOX: Installing Portainer"

if [ ! -e /root/portainer-templates ]; then
    git clone https://github.com/psy0rz/portainer-templates.git /root/portainer-templates
fi

cd /root/portainer-templates/core
if ! [ -e .env ]; then
    cp .env-example .env
fi

docker compose up -d 

echo
echo "ALPINEBOX: Portainer installed"
echo
echo "ALPINEBOX: Please go to /root/portainer-templates/core/, edit ths .env file  and use 'docker compose up -d' to finish the setup"
echo "ALPINEBOX: Login to portainer with admin/admin, set this as the template URL: https://raw.githubusercontent.com/psy0rz/portainer-templates/main/templates.json"

