name: Build image

on:
  
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cd devtools/docker
        chmod +x ./build.sh
        sudo ./build.sh

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }} # This is the upload URL for the release assets
        asset_path: /tmp/alpine.img.gz
        asset_name: alpine.img.gz
        asset_content_type: application/gzip
